### ISSUE TITLE
where's the loader sources?

### ISSUE THREAD

**Issue by catnikita255** [DennisStanistan/NFSScript#3]
.

**Comment by berkay2578** [comment]
See #1, just e-mail him for it as he says it still needs improvements.

**Comment by DennisStanistan** [comment]
Due to security purposes and convenience I've decided not to release the source for the loader.

**Comment by berkay2578** [comment]
Why decide not to release the source for the loader? Furthermore, why one of the reasons is "security" while even script hooks for triple-A current titles are open-source (e.g., OpenVHook or Ultimate ASI Loader)? Your loader is managed-IL, anyone can read the converted code with the simplest tools. It _is_ still your project but you might want to re-think your decision on this as it will only hurt the project in the long run IMO.

**Comment by DennisStanistan** [comment]
While script hooks for the current triple-A titles are open-source, NFSScript works a bit different. There is so much I can say about security & decompiling but that's a whole different topic. Security reasons aside, I see no reason to release the source code for NFSScriptLoader since it only loads the scripts and handles events. After the beta update most of the NFS games running on EAGL engine will be supported (Games built on different engines would have their own loader executable and script dll). I hope this clears everything up.

**Comment by berkay2578** [comment]
>  I see no reason to release the source code for NFSScriptLoader since it only loads the scripts and handles events. 

Yes and that is precisely why you should open-source it. Functions like WaitForGameLoad(), ApplyIntPtrs() may need custom implementations for different titles—I know it is necessary for NFS: World since there isn't a way for one to figure out whether the game has loaded from the memory, it needs feedback from a server emulator after the event POST SecureLoginPersona—or someone else might need to add their own custom events like OnPowerupActivated, it causes ambiguity because you can define a completely new event inside NFSScript but cannot get it to execute because NFSScriptLoader doesn't handle it.

The point is, there will always be something that you cannot foresee that someone will need.

**Comment by DennisStanistan** [comment]
>Functions like WaitForGameLoad(), ApplyIntPtrs() may need custom implementations for different titles
Already got taken care of that.

>I know it is necessary for NFS: World since there isn't a way for one to figure out whether the game has loaded from the memory, it needs feedback from a server emulator after the event POST SecureLoginPersona.

The whole point of WaitForGameLoad() is to make the loader wait until the game has loaded to allow functions like Pre() Initialize() and Main() to get called in case a modder wants to change something before the player logs into a persona.

>Someone else might need to add their own custom events like OnPowerupActivated, it causes ambiguity because you can define a completely new event inside NFSScript but cannot get it to execute because NFSScriptLoader doesn't handle it.

It's still possible to contribute without the loader files by adding the necessary events and memory addresses and allow me to implement it to the loader because at the end of day it is my wonderful little project. You can handle custom events in the script itself using the same method I used in the loader.

`
static byte savedOnPowerActivated = 0;
static IntPtr powerActivatedMemory = 0x010001;

public override void Update()
{
  byte powerActivatedValue = memory.ReadByte(powerActivatedMemory);
  if(powerActivatedValue != savedOnPowerActivated)
  {
     OnPowerupActivated();
     savedOnPowerActivated = powerActivatedValue;
  }
}


public static void OnPowerupActivated()
{
  Log.Print("Event", "Powerup Activated");
}
`

At the moment NFSScript isn't ready for specific game events such as OnPowerupActivated or OnEnterReplayMode because of how the class `Mod` is implemented. Until I solve most of the issues that NFSScript currently has and come up with an easy modding solution, you'll have to stick to simple workarounds.

**Comment by berkay2578** [comment]
Alright, seems fair enough. Thanks for the peaceful discussion. (:
